<?php

namespace ContainerXyx1pwM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_W3TuLasService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.w3TuLas' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.w3TuLas'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'post' => ['privates', '.errored..service_locator.w3TuLas.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.w3TuLas": it references class "App\\Entity\\Post" but no such service exists.'],
        ], [
            'em' => '?',
            'post' => 'App\\Entity\\Post',
        ]);
    }
}
