<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXyx1pwM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXyx1pwM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXyx1pwM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXyx1pwM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXyx1pwM\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xyx1pwM',
    'container.build_id' => 'a45f6d94',
    'container.build_time' => 1643203996,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXyx1pwM');
